### PR TITLE
ENH first set of outputs

### PR DESCRIPTION
**Pull request by beckermr**
This PR has a first set of outputs for CFEP-13. You can see a summary here: https://github.com/conda-forge/feedstock-outputs/blob/first-set/scripts/final_outputs.txt

I based the outputs on the "too big to fail" CFEP plus a few extra things.

to add:
- [x] osx gfortran compilers
- [x] conda smithy

### CODE REVIEW

**Comment by beckermr** [comment]
cc @isuruf @conda-forge/core for comments

**Comment by jakirkham** [comment]
Ah! So can we use to fix the package listing on the webpage?

**Comment by beckermr** [comment]
Sure yeah

**Comment by isuruf** [comment]
I think we should do the other way. `output -> feedstocks` since we need to search using the output name for duplicates.

**Comment by beckermr** [comment]
I don't think that matters @isuruf. In practice, we will get a request from a feedstock and then we will have to validate the outputs. This way, we can simply lookup the allowed outputs in the feedstocks json blob.

**Comment by beckermr** [comment]
The search can be done with a reversed mapping in memory.

**Comment by isuruf** [comment]
True, but then you have to read all of the files and update the mapping. Also from a human perspective, you can search easily.

**Comment by beckermr** [comment]
Right, so the current way optimizes i/o for validation when no new outputs are present whereas the other way optimizes i/o for adding new outputs. I was guessing the former was more common than the later in the end, but might not be at first. 

I don't actually care so I'll switch.

**Pull request merged**
