### PR TITLE
Delete pyarrow.json

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by isuruf** [comment]
Should this be `pyarrow` and `arrow-cpp` instead?

**Comment by beckermr** [comment]
What do you mean?

**Comment by isuruf** [comment]
Until `pyarrow-feedstock` is archived, we should keep supporting it.

**Comment by xhochy** [comment]
I'll archive it tomorrow morning when I merge the PR to `arrow-cpp`. I don't expect rebuilds to happen for older releases. If they happen, we can also revisit here.

**Comment by beckermr** [comment]
Ahhhh. Removing an output here does not deprecate support. If someone pushes a build between now and tomorrow, then the output will get readded. If that did happen, we would simply have to remove it again.

**Comment by beckermr** [comment]
If we added the same output back with a different feedstock, that will remove support. If we know the new feedstock name, we can append it to current outputs to support both.

**Comment by isuruf** [comment]
New feedstock name is `arrow-cpp`. Old one is `pyarrow`.

**Pull request merged**
