### PR TITLE
handle heavydb-ext rename

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

See https://github.com/conda-forge/omniscidb-feedstock/issues/96

### CODE REVIEW

**Comment by jaimergp** [comment]
@pearu @tupui

**Comment by tupui** [comment]
Thank you. Is the outcome of this PR going to archive the old feedstock in favor of the new one?

**Comment by jaimergp** [comment]
Archival needs to be requested separately. This is only to ensure the new feedstock has permissions to produce the outputs that were previously generated in the omniscidb feedstock (hence "claimed" first by that one).

**Comment by tupui** [comment]
Do we need to do anything else here?

**Pull request merged**
