### PR TITLE
update language-specific models for spacy-models feedstock

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

References:
- follow-on to https://github.com/conda-forge/staged-recipes/pull/18840
- should fix up https://github.com/conda-forge/spacy-models-feedstock/issues/1

cc:
@conda-forge/spacy-model-de
@conda-forge/spacy-model-es
@conda-forge/spacy-model-fr
@conda-forge/spacy-model-nl
@conda-forge/spacy-model-pt
@conda-forge/spacy-model-xx

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @beckermr @chrisburr

**Comment by beckermr** [comment]
We should add entries instead of replacing them.

**Comment by jakirkham** [comment]
I thought the original feedstocks were being deprecated though?

**Comment by beckermr** [comment]
Yes but it is good to have a record. Plus they will still work if ever unarchived.

**Comment by jakirkham** [comment]
> Yes but it is good to have a record.

Makes sense.

> Plus they will still work if ever unarchived.

Should they though? Might be strange to have both feedstocks able to push the same packages.

**Comment by beckermr** [comment]
We have cases like this already.

**Comment by jakirkham** [comment]
Sure understand we are doing this. However the question is whether this is good practice or if it should change?

Having two feedstocks actively able to push to the same name makes it hard to track down issues to the right feedstock. This doesn't seem desirable. Is there a use case where this is helpful behavior?

**Comment by beckermr** [comment]
Yes. Many mutexes and compilers need this.

**Comment by bollwyvl** [comment]
> @beckermr We should add entries instead of replacing them.

Updated!

**Pull request merged**
